version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: x
      POSTGRES_PASSWORD: x
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/pgdata
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

volumes:
  postgres:
